server:
  port: ${PORT:8094}

management:
  endpoints:
    web:
      base-path: "/"

  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: Judicial reference data blob store sync API
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  batch:
    initialize-schema: always
  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration,classpath:db/postgres
    schemas: dbjuddata

  mail:
    from: no-reply@reform.hmcts.net
    to:  Praveen.Saxena@HMCTS.NET
    subject:  Exception received at Rout
    host: mta.reform.hmcts.net
    port: 25
    enabled: false
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    min-idle: 1
    max-life: 600000
    idle-timeout: 30000
    maximum-pool-size: 5
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

  profiles:
    include:
      - jrd-router-orchestartion
      - jrd-leaf-router

azure:
  storage:
    account-name: ${ACCOUNT_NAME:ACCOUNT_NAME}
    account-key: ${ACCOUNT_KEY:ACCOUNT_KEY}
    container-name: ${CONTAINER_NAME:CONTAINER_NAME}
    blob-url-suffix: ${BLOB_URL_SUFFIX:BLOB_URL_SUFFIX}

aggregation-strategy-completion-size: 100
aggregation-strategy-timeout: 2000
start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: azure-blob://${azure.storage.account-name}/jud-ref-data-archive
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
archival-file-names: Personal,Appointments
archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy--HH-mm
file-read-time-out: 180000
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
scheduler-audit-select: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date
invalid-exception-sql: insert into dataload_exception_records(file_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) values(?, ?, ?, ?, ?)
invalid-jsr-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp) values(?, ?, ?, ?, ?, ?, ?)
jsr-threshold-limit: 100
scheduler-insert-sql:  insert into dataload_schedular_audit (scheduler_name,scheduler_start_time,scheduler_end_time,scheduler_status)

start-leaf-route: direct:leaf
leaf-route-names: judicial-role-type,judicial-contract-type,judicial-region-type,judicial-base-location_type
scheduler-name: judicial_leaf_scheduler
audit-enable: true
leaf-archival-route: direct:jrdLeafArchival
leaf-archival-file-names: Roles,Contracts,Locations,BaseLocations

