server:
  port: ${PORT:8092}

spring:
  application:
    name: Judicial reference data blob store sync API
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson.date-format: yyyy-MM-dd
  flyway.enabled: true
  flyway.locations: classpath:db/migration,classpath:db/postgres

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

# Scheduler configuration
scheduler:
  config: ${CRON_SCHEDULE:*/1000 * * * * *}
  config2: ${CRON_SCHEDULE:*/1000 * * * * *}

### dependency configuration
auth.provider.service.client.baseUrl: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:K6KA6PRLRFWQLSD6}
    microservice: rd_professional_api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/search/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
    - "/camel/routes/**"
  authorisedServices:
    - rd_professional_api
    - rd_user_profile_api

azure:
  storage:
    account-name: ${ACCOUNT_NAME:rddemo}
    account-key: ${ACCOUNT_KEY:Vjmr3Yk0DUrygumP7FKJ2eUiOyhWvZ5XczDMk13J+m9vtk2IOXEcOlfjlcTaHDb5mHwAsq7qOYf3GtxEo/uFIA==}
    container-name: ${CONTAINER_NAME:jrdtest}
    https-enabled-url: ${HTTPS_ENABLED_URL:false}
    blob-url: ${BLOB_URL:http://rddemo.blob.core.windows.net}
    blob-https-url: ${BLOB_HTTPS_URL:http://rddemo.blob.core.windows.net}

gpg:
  public-key: ${GPG_PRIVATE_KEY:mQENBF3MI6EBCADuKsNuGGS8qtYTLNN62JILWvfO35ahsFEbRx5lx2ZUme5sJcZj
    GWjPybzFi5mRqPy+HGurX04hI9kl5cR2Hg/rZCqF6l01x1uaZ2g69fFvDtGbx5zN
    bA83m40FkVzj2wdBKydmzcF4FmTGAG5FdaR7sGu/9Br4MMMelQ9If1/d5S0zeyNs
    80cwaGhp53TMvx3ABOzC9X++2XjY7tcB6doPXy5wD9obGKveHbwsWTPMY6DHF+ER
    P8DxAjO1dZbYY25gRKwNWkTlzxPMY4SecbsuxUNnRACSTaIeahZ9UoX0SBRngQBU
    EJc6kEuAoMqtXmyBqfWPh3aKbd+NOeA+j4V5ABEBAAG0JVNocmVlZGhhciA8c2hy
    ZWVkaGFyLmxvbXRlQGhtY3RzLm5ldD6JAVQEEwEIAD4WIQQLU413NGhEYBvZ8Mgx
    oyCi0LqbzAUCXcwjoQIbAwUJA8JnAAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
    CRAxoyCi0LqbzP1qB/9xct4Dn8msWVMAg0rDMK5xuPIZp/ZOcZLLlcKFcPUwYYNV
    dhGEao0jGvaUroVDIXHI3KNVeFcIcY2gEmwEup6/HPXidir8IEdX60piP8/tBkGW
    pPpyF+I9BtAOxoIwEbl4SN137vl6APqGcIODwaWk8E4xLdt84Wq0Zld9sF2qGHa6
    sOIkn0vj6ImQI8g0Hz81lacKpZoMnD7qp4Jo0xO/obBvPx+0UfM5JA1aTU1B8jPJ
    ToCHnJz4Eg7+bhashhIsO9S3hS6PGxNGAUmWef3ShMmXhavCHKfE0GJA5EdePUYA
    sJoN2YPEyBKtOfdk6zC127uDALAu7emEP0kolmonuQENBF3MI6EBCADc2sV2hE5K
    1cDQ8C0GQKQDCrDaJUGwjBOsrq+pNf8WjN/BUg6l2SNSL97RpoP2lXiT5J4LOukR
    xTOayjmT6w+yr53c+GRTmVK8aQM3IaMcmiSWXOdSfQOngHlfim+Y87zy4q8RSdXE
    yc+Zwa2vsuoswmSEh8YDVwxF/41j9JVppjKFWy0/fsYv7zV6TTMOV4vGaOBZKVoB
    PfNbBM/tK2t/LNLsLuhxvnH00jVXCfnH0irHlHJs8/tGxWsNUp+C6C94sT7yWbyK
    UG0Gx6+dBo/iDvwskBMF68JAv3C2xu7lJKnZQCfPKVpd30Z18BiSfh7ihfTTta7e
    NE7Nok78bGaxABEBAAGJATwEGAEIACYWIQQLU413NGhEYBvZ8MgxoyCi0LqbzAUC
    XcwjoQIbDAUJA8JnAAAKCRAxoyCi0LqbzNnHB/4guw1mEgHS7TirO+pHuunLUG6H
    czHi2Pj2kw9fwyRAPA/EAlzLgJJqh6S6xQRgTYA2qft96mIaW4JueX/6R9QIcxx2
    4S5vXWy4HuS4C5AUxQ/JAqMbQ79cU3UFPZtYAsw053Z8bb3nQRw7kK9vVZJz4KPU
    WO48kbAYbNvsl9NPk04qQGnMY4pijRqD1n9FuO70b7gpqSFUjwSY7JikYqUXMPR7
    Zgj60koZpkOw3DKGj+EmoChHMKbxWwhrOHnzNovCCagzktJN1gjg3KhEUBQxjCdO
    tEwnYjaTRc2ta/dOS+qCUnbf1HDCKU+yViAhSLNEmkP3rRIxPs+fQF8HNvYQ
    =bBMt}

  private-key: ${GPG_PRIVATE_KEY:lQPGBF3MI6EBCADuKsNuGGS8qtYTLNN62JILWvfO35ahsFEbRx5lx2ZUme5sJcZj
    GWjPybzFi5mRqPy+HGurX04hI9kl5cR2Hg/rZCqF6l01x1uaZ2g69fFvDtGbx5zN
    bA83m40FkVzj2wdBKydmzcF4FmTGAG5FdaR7sGu/9Br4MMMelQ9If1/d5S0zeyNs
    80cwaGhp53TMvx3ABOzC9X++2XjY7tcB6doPXy5wD9obGKveHbwsWTPMY6DHF+ER
    P8DxAjO1dZbYY25gRKwNWkTlzxPMY4SecbsuxUNnRACSTaIeahZ9UoX0SBRngQBU
    EJc6kEuAoMqtXmyBqfWPh3aKbd+NOeA+j4V5ABEBAAH+BwMCoQ+iEmcEuHbptih/
    9OkwSxbl6I3UGoPaviNjZSTSrm2HcQaGmu87QCFwIAYGatrPwiO+hf//bXFcMaGP
    IO6LxbV72Q+4GKcn/ybTn4SUtjHEDktPIp8Hkp+JMaK2U5D/RX3jN0+FANJNVb4g
    +fOPtdnHL+fxE+QnDZQq8ooUoF6EscSMsZmvVyobJT0wzn+7g6cxx93g3T9ZcaPT
    4KiRQZcnX1SdbtlGt6xI0e0Y9iQ1vhKrQHGK8/2OOuKCTdfw1wenHuNqghD7znVf
    i1LMXwcxJj+2r8TtnXLbHoXjwhneA4bgIdDyayLjbYvMUD5oN8LU+RI/ym3e2DC0
    JoXTNrgPGioabtIRaLM4rpeu73IqvBtMY4/KmO4R8XhBjh6ceUrwHBfVvCWP7lFv
    U20c9wYnjVRNtaHTRCq9QmdQVX8t1mx3qBaKfurb39jm3voEOhuJAKpHb89ivFm6
    kP/G+HGzSus9YdjM1PjCpDHCnX/5dJ3Rc0C2SHtulb3b5LaO37LuXxscS1QLd3yw
    MNZhIfJ3rPDg9yHFONtpvFC3P19H97w+Tt+TCk6MOixiBWRyZtpjrggb+NML9Vrh
    S+WDGtXtM6ZLwEr0AFNHG4bsGawiSglnBiMSOpWhh+aTf2PSFTOTtZHz7UbTHBMO
    XBmw+/sGZzDYTKUio6Lnm1qhScLYhnUAKVuFUQ6HbNV/ZkmD+TF1+RpiIYXw6NGr
    S+aHF3OxTPlwbM4pXgrmwvw5qxx/l9kWAgwdM40Iip5e6hoNPyqFWYKZXycz4yvP
    nWsUvIKoLkl0Sb8uDPsgUBB5KB9LvacUYBaYJ5pgXgOBU6/5CgzGWgQkxSJtHPA6
    qdKFl7qB6QXoQ2JgNdITku5XDS0yHwIlO+x5qa/wWIXW6Pze4YJ3+zQQ8k6Z87rU
    sJ93VeySsN+BtCVTaHJlZWRoYXIgPHNocmVlZGhhci5sb210ZUBobWN0cy5uZXQ+
    iQFUBBMBCAA+FiEEC1ONdzRoRGAb2fDIMaMgotC6m8wFAl3MI6ECGwMFCQPCZwAF
    CwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQMaMgotC6m8z9agf/cXLeA5/JrFlT
    AINKwzCucbjyGaf2TnGSy5XChXD1MGGDVXYRhGqNIxr2lK6FQyFxyNyjVXhXCHGN
    oBJsBLqevxz14nYq/CBHV+tKYj/P7QZBlqT6chfiPQbQDsaCMBG5eEjdd+75egD6
    hnCDg8GlpPBOMS3bfOFqtGZXfbBdqhh2urDiJJ9L4+iJkCPINB8/NZWnCqWaDJw+
    6qeCaNMTv6Gwbz8ftFHzOSQNWk1NQfIzyU6Ah5yc+BIO/m4WrIYSLDvUt4UujxsT
    RgFJlnn90oTJl4WrwhynxNBiQORHXj1GALCaDdmDxMgSrTn3ZOswtdu7gwCwLu3p
    hD9JKJZqJ50DxgRdzCOhAQgA3NrFdoROStXA0PAtBkCkAwqw2iVBsIwTrK6vqTX/
    FozfwVIOpdkjUi/e0aaD9pV4k+SeCzrpEcUzmso5k+sPsq+d3PhkU5lSvGkDNyGj
    HJokllznUn0Dp4B5X4pvmPO88uKvEUnVxMnPmcGtr7LqLMJkhIfGA1cMRf+NY/SV
    aaYyhVstP37GL+81ek0zDleLxmjgWSlaAT3zWwTP7StrfyzS7C7ocb5x9NI1Vwn5
    x9Iqx5RybPP7RsVrDVKfgugveLE+8lm8ilBtBsevnQaP4g78LJATBevCQL9wtsbu
    5SSp2UAnzylaXd9GdfAYkn4e4oX007Wu3jROzaJO/GxmsQARAQAB/gcDAk4wnsfK
    IyWs6Rl87Qx7kW5+S9gOx/gZtmlwMBtjeJG5Kt6Ha6VA6HvA91S26LyEludw726s
    P9ZzvUz20c9qumgyIcLYpA4ZZ73/Z7Curc8eQ4HqhLfTOiyBCw9AWI/Mz2wbfouv
    OURyFET2ALXBoAYzgpiNvtwFhTBz/Siroqoa/P1CYErMJ7eha8Uxa4hk9+7jn57f
    b+g08pofDlx6a1cuMkW7PSPLbffULrAZGgQIg5gyyLaUTSphLtCN35ZO46bhivTo
    c8V7i0gzRpMHmnj06+WdHlerOKjqD7KnFwgeCNQ9R943PfeqDCYbJUl/DpoQjrb9
    Lu4cen6j1eynYEb2XzNAYOcpv1S8NQgwjwE26EGJqTxRW+z13cKCFcEmCpB9XTDi
    MQmPLnIhfYpzRHK80rj1U+MedJ2Bv+zzn3QR1PqnJulCOeRAk13WI0KVgUFtl+ZW
    ZFy1nxgsQ5MUhDFbaKSN/rgUJi7J4afJGDoBCcJO7bnm1SCBnxHRtlWeReeJauUq
    nUl9fx0mUJxcVctPgBvOuZ6qUNOel21ama9Ppa00n20rgZo+s4eE7UA2vd0wTO3D
    nwPqua0tb9QXq6iHBj3fECBEcUbwjR0dOObbMQre/DpD//ERKGP+B4VsihsKrYy+
    BivzAe7fPpgxab6jX5RwQZHLpP+anbhJPOxPwCtsp+PTzkaUf2tV2IeJTLD2N2jt
    HNvkUK/r72vjjW9qzwcJoKae185GQxOfzlgMJmAZVAhO+fQUI/ivjZcAr83/cflg
    VdGYvP9BGTLVwLE7kvaupskTynymwT4izEK3epnJTBTTL9kA8SKyqPA9qLnYwKXi
    v2CvMfBxQiWhyzxYzNXpytGvgZjkEd2R9VXcrhUgtFbxP6F6Qso9nIP2ZjdbC9rU
    ekSUdnG0UjIrRkBrP8sLQokBPAQYAQgAJhYhBAtTjXc0aERgG9nwyDGjIKLQupvM
    BQJdzCOhAhsMBQkDwmcAAAoJEDGjIKLQupvM2ccH/iC7DWYSAdLtOKs76ke66ctQ
    bodzMeLY+PaTD1/DJEA8D8QCXMuAkmqHpLrFBGBNgDap+33qYhpbgm55f/pH1Ahz
    HHbhLm9dbLge5LgLkBTFD8kCoxtDv1xTdQU9m1gCzDTndnxtvedBHDuQr29VknPg
    o9RY7jyRsBhs2+yX00+TTipAacxjimKNGoPWf0W47vRvuCmpIVSPBJjsmKRipRcw
    9HtmCPrSShmmQ7DcMoaP4SagKEcwpvFbCGs4efM2i8IJqDOS0k3WCODcqERQFDGM
    J060TCdiNpNFza1r905L6oJSdt/UcMIpT7JWICFIs0SaQ/etEjE+z59AXwc29hA=
    =dYyj}

  password: ${GPG_PASSWORD:Shreedhar!9}


