job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    FLYWAY_ENABLED: true
    ACCOUNT_NAME: $(BLOB_ACCOUNT_NAME)
    ACCOUNT_KEY: $(BLOB_ACCESS_KEY)
  postgresql:
    postgresqlUsername: dbjuddata
    postgresqlPassword: dbjuddata
    postgresqlDatabase: dbjuddata
    #Whether to deploy the Postgres Chart or not
    enabled: true
  kind: CronJob
  schedule: "*/5 * * * *"
  global:
    jobKind: CronJob
  keyVaults:
    rd:
      secrets:
        - CONTAINER-NAME
        - BLOB-URL-SUFFIX
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
blobstorage:
  resourceGroup: rd
  teamName: "RD"
  location: uksouth
  setup:
    containers:
    - jud-ref-data
    - jud-ref-data-archive
  enabled: true
